#!/bin/bash

# Written by Karolis Uziela in 2014

script_name=`basename $0`

if [ $# != 2 ] ; then
    echo "
Usage: 

$script_name <svm_light_file> <txt_file>

"
    exit 1
fi

input_file=$1
output_file=$2

sed -e 's/[0-9]*://g' $input_file >$output_file
