#!/bin/bash

# Written by Karolis Uziela in 2014

script_name=`basename $0`

if [ $# != 2 ] ; then
    echo "
Usage: 

$script_name <input_file> <output_file>

"
    exit 1
fi

input_file=$1
output_file=$2

cat $input_file | awk '{for (i = 1; i <= NF; i++) { if ($i<0) {printf "0 "} else if ($i>1) {printf "1 "} else {printf $i" "} } ; print "" }' >$output_file
