#!/bin/sh

setvar() { eval $1="'$3'" ; }

set -ue
set -x

setvar FTP_SITE = ftp.wwpdb.org
setvar FTP_DIR  = pub/pdb/data/structures/all/pdb

for entry in ${1+"$@"}
do
    filebase=`echo $entry | awk '{print tolower($0)}'`
    setvar filename = pdb${filebase}.ent.gz
    wget --passive --tries=0 ftp://${FTP_SITE}/${FTP_DIR}/$filename
    gzip -dc ${filename} > ${entry}.pdb
    rm -f ${filename}
done
